name: Build Rust App

# 触发条件：推送到 main 分支，或者提交 PR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: mc_translator

jobs:
  build:
    name: Build - ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: mc_translator.exe
            name: mc-translator-x86_64-windows.exe

          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: mc_translator
            name: mc-translator-x86_64-linux

          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: mc_translator
            name: mc-translator-x86_64-macos

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libssl-dev pkg-config

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Cache Cargo registry
        uses: swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Rename and Move Binary
        shell: bash
        run: |
          mkdir -p output
          cp target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} output/${{ matrix.platform.name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: output/${{ matrix.platform.name }}
          if-no-files-found: error